before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) --path=deps "${FLAGS[@]}"
  - bundle clean

test:2.6:
  image: ruby:2.6
  script: bundle exec rake test XML_BACKEND=REXML 2>/dev/null && bundle exec rake test XML_BACKEND=Oga 2>/dev/null && bundle exec rake test XML_BACKEND=Nokogiri 2>/dev/null
  except:
    - tags
  cache:
    key: ruby:2.6
    paths:
      - deps

test:2.7:
  image: ruby:2.7
  script: bundle exec rake test XML_BACKEND=REXML 2>/dev/null && bundle exec rake test XML_BACKEND=Oga 2>/dev/null && bundle exec rake test XML_BACKEND=Nokogiri 2>/dev/null
  except:
    - tags
  cache:
    key: ruby:2.7
    paths:
      - deps

test:3.0:
  image: ruby:3.0-rc
  script: bundle exec rake test XML_BACKEND=REXML 2>/dev/null && bundle exec rake test XML_BACKEND=Oga 2>/dev/null && bundle exec rake test XML_BACKEND=Nokogiri 2>/dev/null
  except:
    - tags
  cache:
    key: ruby:3.0
    paths:
      - deps

pages:
  stage: deploy
  image: ruby:2.7
  dependencies:
    - test:2.6
  script:
    - bundle exec rake test doc:yard
    - mv doc public
    - mv coverage public/
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    key: ruby:2.7
    paths:
      - deps
