before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) --path=deps "${FLAGS[@]}"
  - bundle clean

test:2.3:
  image: ruby:2.3
  script: bundle exec rake test XML_BACKEND=REXML && bundle exec rake test XML_BACKEND=Oga && bundle exec rake test XML_BACKEND=Nokogiri
  except:
    - tags
  cache:
    key: ruby:2.3
    paths:
      - deps

test:2.4:
  image: ruby:2.4
  script: bundle exec rake test XML_BACKEND=REXML && bundle exec rake test XML_BACKEND=Oga && bundle exec rake test XML_BACKEND=Nokogiri
  except:
    - tags
  cache:
    key: ruby:2.4
    paths:
      - deps

test:2.5:
  image: ruby:2.5
  script: bundle exec rake test XML_BACKEND=REXML && bundle exec rake test XML_BACKEND=Oga && bundle exec rake test XML_BACKEND=Nokogiri
  except:
    - tags
  artifacts:
    paths:
      - coverage
  cache:
    key: ruby:2.5
    paths:
      - deps

test:2.6:
  image: ruby:2.6
  script: bundle exec rake test XML_BACKEND=REXML && bundle exec rake test XML_BACKEND=Oga && bundle exec rake test XML_BACKEND=Nokogiri
  except:
    - tags
  cache:
    key: ruby:2.6
    paths:
      - deps

pages:
  stage: deploy
  dependencies:
    - test:2.6
  script:
    - bundle exec rake test doc:yard
    - mv doc public
    - mv coverage public/
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    key: ruby:2.6
    paths:
      - deps
