before_script:
  - apt-get update -qq && apt-get install zip
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) "${FLAGS[@]}"

test:
  script:
    - bundle exec rake test
