variables:
  LANG: ja_JP.UTF-8

before_script:
  - apt-get update -qq && apt-get install -y zip
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs=$(nproc) "${FLAGS[@]}"

test:2.2:
  image: ruby:2.2
  script:
    - bundle exec rake test

test:2.3:
  image: ruby:2.3
  script: bundle exec rake test

test:2.4:
  image: ruby:2.4
  script: bundle exec rake test
