version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem fetch zipruby --platform mswin32
  - gem install ./zipruby-0.3.6-x86-mswin32.gem
  - bundle install --system

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
